language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

script:
  - go vet ./...
  - go test -v ./cmd/... ./utils/logevent/... ./filter/... ./input/... ./output/...
  - go build 