language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

script:
  - go vet ./...
  - go test -v ./utils/logevent/... ./filter/... ./input/... ./output/... -covermode=count -coverprofile=coverage.out
  - go build 
after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN